# SPDX-FileCopyrightText: 2023 Linnea Gräf <nea@nea.moe>
#
# SPDX-License-Identifier: CC0-1.0

name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
    validation:
        name: "Validation"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout repository
            - uses: gradle/actions/wrapper-validation@v4
              name: Validate wrappers
